### PR TITLE
Doc updates

### PR DESCRIPTION
**Pull request by vvaldez**

### CODE REVIEW

**Comment by purpleidea** [comment]
Hey @vvaldez thanks for another doc patch, this is awesome!

Before I do a more thorough review/merge, could you rebase this against current git master and squash it into a relevant number of patches (one or as many as you like, but please remove the merge commits).

Thanks!
James

**Comment by vvaldez** [comment]
Sure! Let me figure that out.

**Comment by vvaldez** [comment]
How about now?

**Comment by purpleidea** [comment]
@vvaldez Patch looks rebased nicely Great!!

Looking at the content, a number of sections (looks like the terminal output mostly) are indented with spaces, but it's not necessary for any reason I know... Did I miss something?

The table is a cute touch, but I don't think it's formatted correctly... run 'make docs' and it should generate a copy you can view. The $ dissappears, and other things...

LMK,
Thanks!

**Comment by vvaldez** [comment]
Oops, I didn't try to make the docs. The indent was to distinguish between prompt and output since the getfacl uses hashes, but it's not necessary. I'll fix.

**Comment by purpleidea** [comment]
On Thu, Jul 9, 2015 at 10:03 AM, Vinny Valdez <notifications@github.com>
wrote:

> Oops, I didn't try to make the docs. The indent was to distinguish between
> prompt and output since the getfacl uses hashes, but it's not necessary.
> I'll fix.



Ah, got it.
We should probably leave it without the indents so it looks exactly as
normal terminal output would. Whether that looks sane or not is getfact's
fault, now ours.

LMK when I should review again.

**Comment by vvaldez** [comment]
How does this look?

**Comment by purpleidea** [comment]
Done review. Needs a few fixes. Thanks again for the patch!

**Comment by vvaldez** [comment]
Ready for review again.

**Comment by purpleidea** [comment]
w00t!

Merged, thanks!

**Pull request closed without merging**
